export interface District {
  leaid: string;
  name: string;
  state: string;
  city: string | null;
  enrollment: number | null;
  frpl_rate: number | null;
  ell_pct: number | null;
  swd_pct: number | null;
  white_pct: number | null;
  math_proficiency: number | null;
  read_proficiency: number | null;
  chronic_absenteeism: number | null;
  graduation_rate: number | null;
  expenditure_per_pupil: number | null;
  student_teacher_ratio: number | null;
  number_of_schools: number | null;
  locale_code: number | null;
  enrollment_trend_3yr: number | null;
  staffing_trend_3yr: number | null;
  ell_trend_3yr: number | null;
  charter_payments: number | null;
  private_payments: number | null;
  charter_enrollment: number | null;
  debt_outstanding: number | null;
  lifetime_vendor_rev: number;
  vendor_count: number;
  is_customer: boolean;
  has_open_pipeline: boolean;
  owner: string | null;
  fit_score: number;
  value_score: number;
  readiness_score: number;
  state_score: number;
  composite_score: number;
  tier: string;
  fit_details: string;
  value_details: string;
  readiness_details: string;
  state_details: string;
}
