/**
 * Generates src/features/news/lib/publisher-states.generated.ts by mining
 * existing news_article_districts links: a publisher whose links concentrate
 * ≥70% in one state (≥10 articles) is treated as a state-local publisher.
 *
 * Used by the news matcher as a state hint when the article title doesn't
 * contain a state name. See src/features/news/lib/state-hints.ts.
 *
 * Usage:
 *   npx tsx scripts/generate-publisher-state-map.ts
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { PrismaClient } from "@prisma/client";

const MIN_ARTICLES = 10;
const MIN_SHARE = 0.7;

const prisma = new PrismaClient();

interface Row {
  source: string;
  state_abbrev: string;
  n: bigint;
  total: bigint;
}

async function main() {
  const rows = await prisma.$queryRaw<Row[]>`
    WITH ps AS (
      SELECT na.source, d.state_abbrev, COUNT(*)::bigint AS n
      FROM news_articles na
      JOIN news_article_districts nad ON nad.article_id = na.id
      JOIN districts d ON d.leaid = nad.leaid
      WHERE d.state_abbrev IS NOT NULL
      GROUP BY na.source, d.state_abbrev
    ),
    tot AS (SELECT source, SUM(n)::bigint AS total FROM ps GROUP BY source),
    ranked AS (
      SELECT ps.source, ps.state_abbrev, ps.n, tot.total,
        ROW_NUMBER() OVER (PARTITION BY ps.source ORDER BY ps.n DESC) AS rk
      FROM ps JOIN tot ON tot.source = ps.source
    )
    SELECT source, state_abbrev, n, total
    FROM ranked
    WHERE rk = 1
      AND total >= ${MIN_ARTICLES}
      AND (n::numeric / total) >= ${MIN_SHARE}
    ORDER BY total DESC, source ASC
  `;

  console.log(`[generate-publisher-states] qualifying publishers: ${rows.length}`);

  // Sort alphabetically for stable file diffs.
  const sorted = [...rows].sort((a, b) => a.source.localeCompare(b.source));

  const entries = sorted
    .map((r) => `  ${JSON.stringify(r.source)}: ${JSON.stringify(r.state_abbrev)},`)
    .join("\n");

  const contents = `// Auto-generated by scripts/generate-publisher-state-map.ts — do not edit by hand.
// Regenerate whenever the corpus has materially shifted.
//
// Each key is a publisher (matches news_articles.source) whose existing
// district links concentrate ≥${Math.round(MIN_SHARE * 100)}% in one state with
// ≥${MIN_ARTICLES} total linked articles. Used as a state hint by the news matcher
// when the article title lacks a state name.

export const PUBLISHER_STATES: Record<string, string> = {
${entries}
};
`;

  const out = resolve(
    __dirname,
    "..",
    "src",
    "features",
    "news",
    "lib",
    "publisher-states.generated.ts"
  );
  writeFileSync(out, contents);
  console.log(`Wrote ${sorted.length} publishers to ${out}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
