/**
 * Generates src/features/news/lib/acronyms.generated.ts by querying the districts
 * table and matching known acronyms to their real LEAIDs.
 *
 * Usage: `npx tsx scripts/generate-acronym-map.ts`
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { PrismaClient } from "@prisma/client";

// Candidate acronym → name-fragment lookups. Matches the District.accountName
// or District.name via fuzzy contains; first hit in the target state wins.
const CANDIDATES: Array<{ acronym: string; state: string; nameLike: string }> = [
  { acronym: "CPS", state: "IL", nameLike: "Chicago" },
  { acronym: "LAUSD", state: "CA", nameLike: "Los Angeles Unified" },
  { acronym: "NYCDOE", state: "NY", nameLike: "New York City" },
  { acronym: "HISD", state: "TX", nameLike: "Houston Independent" },
  { acronym: "MCPS", state: "MD", nameLike: "Montgomery" },
  { acronym: "DCPS", state: "DC", nameLike: "District of Columbia" },
  { acronym: "PGCPS", state: "MD", nameLike: "Prince George" },
  { acronym: "CMS", state: "NC", nameLike: "Charlotte-Mecklenburg" },
  { acronym: "DISD", state: "TX", nameLike: "Dallas Independent" },
  { acronym: "BPS", state: "MA", nameLike: "Boston" },
  { acronym: "FCPS", state: "VA", nameLike: "Fairfax" },
  { acronym: "JCPS", state: "KY", nameLike: "Jefferson" },
  { acronym: "SDP", state: "PA", nameLike: "Philadelphia" },
  { acronym: "SFUSD", state: "CA", nameLike: "San Francisco Unified" },
  { acronym: "OUSD", state: "CA", nameLike: "Oakland Unified" },
  { acronym: "SDUSD", state: "CA", nameLike: "San Diego Unified" },
  { acronym: "MDCPS", state: "FL", nameLike: "Miami-Dade" },
  { acronym: "BCPS", state: "MD", nameLike: "Baltimore County" },
  { acronym: "AACPS", state: "MD", nameLike: "Anne Arundel" },
  { acronym: "LCPS", state: "VA", nameLike: "Loudoun" },
  { acronym: "WCPSS", state: "NC", nameLike: "Wake County" },
  { acronym: "GCS", state: "NC", nameLike: "Guilford County" },
  { acronym: "DPS", state: "CO", nameLike: "Denver Public" },
  { acronym: "APS", state: "GA", nameLike: "Atlanta Public" },
  { acronym: "MPS", state: "WI", nameLike: "Milwaukee" },
  { acronym: "SLPS", state: "MO", nameLike: "St. Louis Public" },
  { acronym: "KCPS", state: "MO", nameLike: "Kansas City Public" },
  { acronym: "TPS", state: "OK", nameLike: "Tulsa" },
  { acronym: "NPS", state: "NJ", nameLike: "Newark" },
  { acronym: "MNPS", state: "TN", nameLike: "Metropolitan Nashville" },
];

const prisma = new PrismaClient();

async function main() {
  const resolved: Array<{ acronym: string; leaid: string; state: string; fullName: string }> = [];

  for (const c of CANDIDATES) {
    const district = await prisma.district.findFirst({
      where: {
        stateAbbrev: c.state,
        name: { contains: c.nameLike, mode: "insensitive" },
      },
      orderBy: { enrollment: "desc" },
      select: { leaid: true, name: true, stateAbbrev: true },
    });
    if (district) {
      resolved.push({
        acronym: c.acronym,
        leaid: district.leaid,
        state: district.stateAbbrev ?? c.state,
        fullName: district.name,
      });
      console.log(`✓ ${c.acronym} → ${district.leaid} (${district.name})`);
    } else {
      console.log(`✗ ${c.acronym}: no match for "${c.nameLike}" in ${c.state}`);
    }
  }

  const contents = `// Auto-generated by scripts/generate-acronym-map.ts — do not edit by hand.
// Regenerate whenever the districts table changes.

export interface AcronymEntry {
  leaid: string;
  state: string;
  fullName: string;
}

export const DISTRICT_ACRONYMS: Record<string, AcronymEntry> = {
${resolved
  .map(
    (r) =>
      `  ${r.acronym}: { leaid: "${r.leaid}", state: "${r.state}", fullName: "${r.fullName.replace(/"/g, '\\"')}" },`
  )
  .join("\n")}
};
`;

  const out = resolve(__dirname, "..", "src", "features", "news", "lib", "acronyms.generated.ts");
  writeFileSync(out, contents);
  console.log(`\nWrote ${resolved.length} entries to ${out}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
